-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 18:53:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema education
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dataschool` ;
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataschool` DEFAULT CHARACTER SET utf8 ;
USE `dataschool` ;

-- -----------------------------------------------------
-- Table `dataschool`.`Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataschool`.`Cursos` ;

CREATE TABLE IF NOT EXISTS `dataschool`.`Cursos` (
  `Nombre` VARCHAR(15) NOT NULL PRIMARY KEY,
  `Descripción` VARCHAR(45) NOT NULL,
  `Foto` BLOB NOT NULL,
  `Horario` VARCHAR(200) NULL,
  `Precio del curso` FLOAT NULL,
  `Descripción del profesor` VARCHAR(200) NOT NULL
);
-- -----------------------------------------------------
-- Table `dataschool`.`Docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataschool`.`Docentes`;

CREATE TABLE IF NOT EXISTS `dataschool`.`Docentes`(
	`Nombre` VARCHAR(50) NOT NULL PRIMARY KEY,
    `Descripción` VARCHAR(200),
    `Foto` BLOB NOT NULL
);
-- -----------------------------------------------------
-- Table `dataschool`.`Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataschool`.`Alumnos`;

CREATE TABLE IF NOT EXISTS `dataschool`.`Alumnos` (
  `Nombre` VARCHAR(50) PRIMARY KEY NOT NULL,
  `DNI` INT NOT NULL,
  `Celular` CHAR(9) NULL
  );
  
-- -----------------------------------------------------
-- Table `dataschool`.`Horario Docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataschool`.`Horario Docentes` ;

CREATE TABLE IF NOT EXISTS `dataschool`.`Horario Docentes` (
  `Docentes_Nombre` VARCHAR(50) NOT NULL,
  `Cursos_Nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY(`Docentes_Nombre`,`Cursos_Nombre`),
  FOREIGN KEY(`Docentes_Nombre`) REFERENCES `dataschool`. `Docentes` (`Nombre`) ON DELETE CASCADE,
  FOREIGN KEY(`Cursos_Nombre`) REFERENCES `dataschool`. `Cursos` (`Nombre`) ON DELETE CASCADE
  );

-- -----------------------------------------------------
-- Table `dataschool`.`Horario Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataschool`.`Horario Alumnos` ;

CREATE TABLE IF NOT EXISTS `dataschool`.`Horario Alumnos` (
  `Cursos_Nombre` VARCHAR(15) NOT NULL,
  `Alumnos_Nombre` VARCHAR(50) NOT NULL, 
  PRIMARY KEY(`Cursos_Nombre`,`Alumnos_Nombre`),
  FOREIGN KEY(`Cursos_Nombre`) REFERENCES `dataschool`. `Cursos` (`Nombre`) ON DELETE CASCADE,
  FOREIGN KEY(`Alumnos_Nombre`) REFERENCES `dataschool`. `Alumnos` (`Nombre`) ON DELETE CASCADE
    );
    

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;