-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 18:53:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dataventas` ;

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataventas` DEFAULT CHARACTER SET utf8 ;
USE `dataventas` ;

-- -----------------------------------------------------
-- Table `dataventas`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataventas`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `dataventas`.`Clientes` (
  `idClientes` INT NOT NULL PRIMARY KEY,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(15) NULL,
  `País` VARCHAR(15) NOT NULL,
  `Celular` CHAR(9) NOT NULL,
  `FAX` VARCHAR(45) NOT NULL,
  `Fecha de ingreso` DATE NOT NULL,
  `ind_vigente` VARCHAR(30) NOT NULL
);

-- -----------------------------------------------------
-- Table `dataventas`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataventas`.`Vendedor`;

CREATE TABLE IF NOT EXISTS `dataventas`.`Vendedor`(
	`idVendedor` INT PRIMARY KEY,
    `Nombre` VARCHAR(45)
);
-- -----------------------------------------------------
-- Table `dataventas`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataventas`.`Pedidos`;

CREATE TABLE IF NOT EXISTS `dataventas`.`Pedidos` (
  `idPedido` INT NOT NULL PRIMARY KEY,
  `FechaPedido` DATE NOT NULL,
  `Subtotal` FLOAT NOT NULL,
  `Impuesto` FLOAT NOT NULL,
  `Total` FLOAT NOT NULL,
  `idClientes` INT NOT NULL,
  `idVendedor` INT NOT NULL,
  FOREIGN KEY (`idClientes`) REFERENCES `dataventas`.`Clientes` (`idClientes`) ON DELETE cascade, 
  FOREIGN KEY (`idVendedor`) REFERENCES `dataventas`.`Vendedor` (`idVendedor`) ON DELETE cascade
  );
  
-- -----------------------------------------------------
-- Table `dataventas`.`Artículo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataventas`.`Artículo` ;

CREATE TABLE IF NOT EXISTS `dataventas`.`Artículo` (
  `idArtículo` INT NOT NULL PRIMARY KEY,
  `Descripción` VARCHAR(100) NOT NULL,
  `Precio Unitario` FLOAT NOT NULL,
  `Stock` INT NOT NULL
  );

-- -----------------------------------------------------
-- Table `dataventas`.`Detalle Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataventas`.`Detalle Pedido` ;

CREATE TABLE IF NOT EXISTS `dataventas`.`Detalle Pedido` (
  `idPedido` INT NOT NULL,
  `idArtículo` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Subtotal` FLOAT NOT NULL,
  PRIMARY KEY (`idPedido`,`idArtículo`),
  FOREIGN KEY (`idPedido`) REFERENCES `dataventas`.`Pedido` (`idPedido`) ON DELETE cascade,
  FOREIGN KEY (`idArtículo`) REFERENCES `dataventas`.`Artículo` (`idArtículo`) ON DELETE cascade
    );


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;